#pragma once
#include <glm/glm.hpp>
#include "terrain.h"

// Static arena geometry, shared by server (collision) and client (collision + render).
// All boxes sit on the ground. Obstacle thickness stays >= 1.0 so bullets
// (max step ~0.85 m per physics tick) cannot tunnel through.
//
// Two maps exist: TRAINING (offline practice, symmetric cover) and WAREHOUSE
// (online matches, PUBG-style yard). The active map is chosen at runtime —
// server forces WAREHOUSE; the client uses TRAINING offline, WAREHOUSE once a
// server state arrives. Collision and render read the gMap* globals below.

struct Box {
    glm::vec3 center;  // y = half.y (resting on ground)
    glm::vec3 half;
};

enum MapId { MAP_TRAINING = 0, MAP_WAREHOUSE = 1, MAP_FIELD = 2 };

// --- TRAINING: the original symmetric arena -------------------------------
inline const Box TRAINING_BOXES[] = {
    // center pillar
    {{ 0.0f, 1.5f,  0.0f}, {1.0f, 1.5f, 1.0f}},
    // walls on the axes
    {{ 6.0f, 1.0f,  0.0f}, {0.6f, 1.0f, 2.5f}},
    {{-6.0f, 1.0f,  0.0f}, {0.6f, 1.0f, 2.5f}},
    {{ 0.0f, 1.0f,  6.0f}, {2.5f, 1.0f, 0.6f}},
    {{ 0.0f, 1.0f, -6.0f}, {2.5f, 1.0f, 0.6f}},
    // crates on the diagonals (low — can be shot over)
    {{ 4.0f, 0.8f,  4.0f}, {0.8f, 0.8f, 0.8f}},
    {{-4.0f, 0.8f,  4.0f}, {0.8f, 0.8f, 0.8f}},
    {{ 4.0f, 0.8f, -4.0f}, {0.8f, 0.8f, 0.8f}},
    {{-4.0f, 0.8f, -4.0f}, {0.8f, 0.8f, 0.8f}},
    // tall pillars on the outer diagonals
    {{ 9.0f, 1.5f,  9.0f}, {0.7f, 1.5f, 0.7f}},
    {{-9.0f, 1.5f,  9.0f}, {0.7f, 1.5f, 0.7f}},
    {{ 9.0f, 1.5f, -9.0f}, {0.7f, 1.5f, 0.7f}},
    {{-9.0f, 1.5f, -9.0f}, {0.7f, 1.5f, 0.7f}},
    // shooting-range target wall (front face at x=25.4); a normal obstacle so the
    // shared collision/render handle it — no training-only physics path.
    {{26.0f, 4.0f,  0.0f}, {0.6f, 4.0f, 13.0f}},
};
inline constexpr int TRAINING_BOX_COUNT = (int)(sizeof(TRAINING_BOXES) / sizeof(TRAINING_BOXES[0]));

// --- WAREHOUSE: enclosed yard, central building, shipping containers -------
// Long axis is X (spawns sit at +/-15 X, facing center). Perimeter walls seal
// the play space; the central block and containers break sightlines.
inline const Box WAREHOUSE_BOXES[] = {
    // central two-story block (solid cover centerpiece)
    {{  0.0f, 2.5f,  0.0f}, {5.0f, 2.5f, 4.0f}},
    // perimeter walls (rectangle: X in [-22,22], Z in [-15,15])
    {{  0.0f, 1.5f,  15.0f}, {22.0f, 1.5f, 0.6f}},   // north
    {{  0.0f, 1.5f, -15.0f}, {22.0f, 1.5f, 0.6f}},   // south
    {{ 22.0f, 1.5f,  0.0f }, {0.6f,  1.5f, 15.0f}},  // east
    {{-22.0f, 1.5f,  0.0f }, {0.6f,  1.5f, 15.0f}},  // west
    // shipping containers (long on X)
    {{-13.0f, 1.25f,  8.0f}, {3.0f, 1.25f, 1.25f}},
    {{ 13.0f, 1.25f,  8.0f}, {3.0f, 1.25f, 1.25f}},
    {{-13.0f, 1.25f, -8.0f}, {3.0f, 1.25f, 1.25f}},
    {{ 13.0f, 1.25f, -8.0f}, {3.0f, 1.25f, 1.25f}},
    // shipping containers (long on Z, flanking the center)
    {{ -9.0f, 1.25f,  0.0f}, {1.25f, 1.25f, 3.0f}},
    {{  9.0f, 1.25f,  0.0f}, {1.25f, 1.25f, 3.0f}},
    // low wooden crates near the building (shoot over)
    {{ -5.0f, 0.75f,  10.0f}, {0.75f, 0.75f, 0.75f}},
    {{  5.0f, 0.75f,  10.0f}, {0.75f, 0.75f, 0.75f}},
    {{ -5.0f, 0.75f, -10.0f}, {0.75f, 0.75f, 0.75f}},
    {{  5.0f, 0.75f, -10.0f}, {0.75f, 0.75f, 0.75f}},
    // pipe/crate stacks by the end walls (near each spawn)
    {{-17.0f, 1.0f,  0.0f}, {1.0f, 1.0f, 2.0f}},
    {{ 17.0f, 1.0f,  0.0f}, {1.0f, 1.0f, 2.0f}},
};
inline constexpr int WAREHOUSE_BOX_COUNT = (int)(sizeof(WAREHOUSE_BOXES) / sizeof(WAREHOUSE_BOXES[0]));

// --- FIELD: 1 km^2 open terrain with procedurally scattered cover -----------
// Rocks/crates are placed deterministically on a coarse grid (hash decides which
// cells get one + the jitter/size) and snapped onto the heightfield so they rest
// on the surface. Reuses the Box collision/render path; regenerated by setMap.
inline constexpr float FIELD_HALF      = 500.0f;  // 1 km across
inline constexpr int   FIELD_BOX_MAX   = 400;
inline Box gFieldBoxes[FIELD_BOX_MAX];
inline int gFieldBoxCount = 0;

inline void generateFieldBoxes() {
    gFieldBoxCount = 0;
    const float CELL = 55.0f;                       // grid spacing between candidates
    const int   R    = (int)(FIELD_HALF / CELL) - 1; // keep clear of the bounds
    for (int gz = -R; gz <= R && gFieldBoxCount < FIELD_BOX_MAX; gz++)
    for (int gx = -R; gx <= R && gFieldBoxCount < FIELD_BOX_MAX; gx++) {
        if (terrHash(gx * 91 + 7, gz * 57 + 13) < 0.45f) continue;   // ~half empty
        float cx = gx * CELL + (terrHash(gx, gz)             - 0.5f) * 38.0f;
        float cz = gz * CELL + (terrHash(gx + 100, gz - 100) - 0.5f) * 38.0f;
        float s  = terrHash(gx * 3, gz * 5);        // 0..1 size roll
        glm::vec3 half = {1.0f + s * 2.5f, 0.8f + s * 2.2f,
                          1.0f + terrHash(gx * 5, gz * 3) * 2.5f};
        glm::vec3 center = {cx, terrainElevation(cx, cz) + half.y, cz};
        gFieldBoxes[gFieldBoxCount++] = {center, half};
    }
}

inline constexpr float ARENA_HALF = 45.0f;  // default hard clamp on X/Z (walls seal sooner)

// --- active map (runtime-selected; default training) ----------------------
inline const Box* gMapBoxes    = TRAINING_BOXES;
inline int        gMapBoxCount = TRAINING_BOX_COUNT;
inline MapId      gMapId       = MAP_TRAINING;
inline float      gArenaHalf   = ARENA_HALF;  // per-map clamp (grows for bigger maps)

inline void setMap(MapId id) {
    gMapId = id;
    gTerrainOn = (id == MAP_FIELD);   // gates terrainHeight() in physics/spawns/render
    if (id == MAP_WAREHOUSE) {
        gMapBoxes = WAREHOUSE_BOXES; gMapBoxCount = WAREHOUSE_BOX_COUNT; gArenaHalf = 45.0f;
    } else if (id == MAP_FIELD) {
        generateFieldBoxes();
        gMapBoxes = gFieldBoxes;     gMapBoxCount = gFieldBoxCount;      gArenaHalf = FIELD_HALF;
    } else {
        gMapBoxes = TRAINING_BOXES;  gMapBoxCount = TRAINING_BOX_COUNT;  gArenaHalf = 45.0f;
    }
}
